 FROM **${release:builder}** AS builder

  WORKDIR /go/src/github.com/openshift/assisted-installer-agent
  COPY . .
  RUN make build

  FROM **${release:base}**

  LABEL io.openshift.release.operator=true

.....

  RUN if [ "$(arch)" -eq "x86_64" ]; then dnf install -y biosdevname dmidecode; fi
  RUN if [ "$(arch)" -eq "aarch64" ]; then dnf install -y dmidecode; fi
  RUN dnf install -y dhclient file findutils fio ipmitool iputils nmap openssh-clients podman chrony smartmontools && dnf clean all
