kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: operator-pipeline-edit
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: okd-team
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
