apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../manifests/tekton/tasks/base
  - ../../../manifests/tekton/pipelines/base
  - ../../../manifests/tekton/triggers/base
namespace: okd-team

patchesJson6902:
- path: patches/patch-envars.yaml
  target:
    group: tekton.dev
    kind: Task
    name: okd-openshift-build-poc
    version: v1beta1

- path: patches/patch-pvc.yaml
  target:
    group: triggers.tekton.dev
    kind: TriggerTemplate
    name: okd-openshift-build-poc-template
    version: v1alpha1

