kind: Pod
apiVersion: v1
metadata:
  name: debug-pod
  namespace: okd-team
spec:
  containers:
  - name: trigger-build
    image: curlimages/curl
    args:
      - curl
      - '-X'
      - POST
      - '--data'
      - '{"url": "https://github.com/openshift/assisted-installer-agent","name": "assisted-installer-agent"","hash": "c9153da1eacf25eb1d85b45c939ac48880d1af6c"}'
      - 'http://el-okd-openshift-build-poc.okd-team.svc.cluster.local:8080'
    resources:
      limits:
        cpu: 200m
        memory: 250Mi
      requests:
        cpu: 200m
        memory: 250Mi
     
